version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - timestamp=$(date +%Y%m%dT%H%M)
      - year=$(date +%Y)
      - month=$(date +%m)
      - day=$(date +%d)
      - hour=$(date +%H)
      - ls -lart
  build:
    commands:
      - echo Entered the build phase...

