apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: game-2048
---
apiVersion: v1
kind: Secret
metadata:
  name: api-service-account-token
  namespace: game-2048
  annotations:
    kubernetes.io/service-account.name: "api-service-account"
type: kubernetes.io/service-account-token
